// AUTO-GENERATED by pipeline/indicator_registry.py — do not edit by hand.
// Regenerate with: python -m pipeline.indicator_registry --export-ts

export interface Indicator {
  code: string;
  label: string;
  domain: string;
  source: string;
  unit: string;
  direction: number;
  interpretation: string;
  pillars: string[];
  benchmarks: Record<string, number>;
  normalization: string;
  reference_url: string;
  available: boolean;
  fallback_code: string | null;
}

export const PILLARS = {
  "macro": "Macroeconomic & fiscal envelope",
  "revenue": "Domestic revenue mobilisation",
  "prioritisation": "Health reprioritisation",
  "external": "External financing & aid transition",
  "debt": "Debt sustainability & crowding-out",
  "efficiency": "Efficiency of spending",
  "pfm": "PFM, governance & absorptive capacity"
} as const;

export const INDICATOR_REGISTRY: Record<string, Indicator> = {
  "NGDP_RPCH": {
    "code": "NGDP_RPCH",
    "label": "Real GDP growth",
    "domain": "macro",
    "source": "IMF WEO",
    "unit": "%",
    "direction": 1,
    "interpretation": "Sustained real GDP growth can expand the public resource envelope, making health budget increases easier to finance. The 2% line is a heuristic, not a formal standard.",
    "pillars": [
      "macro"
    ],
    "benchmarks": {
      "heuristic_floor": 2.0
    },
    "normalization": "peer_minmax",
    "reference_url": "https://www.imf.org/en/Publications/WEO",
    "available": true,
    "fallback_code": null
  },
  "NGDPDPC": {
    "code": "NGDPDPC",
    "label": "GDP per capita (current US$)",
    "domain": "macro",
    "source": "IMF WEO",
    "unit": "US$",
    "direction": 1,
    "interpretation": "Context / peer-grouping variable only \u2014 income LEVEL is not scored into the fiscal-space index (the macro pillar captures growth & price stability, per Tandon-Cashin; level would triple-count with the PPP and World Bank series and proxy everything).",
    "pillars": [
      "macro"
    ],
    "benchmarks": {},
    "normalization": "none",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "PPPPC": {
    "code": "PPPPC",
    "label": "GDP per capita, PPP",
    "domain": "macro",
    "source": "IMF WEO",
    "unit": "intl$",
    "direction": 1,
    "interpretation": "Context / peer-grouping variable only (see GDP per capita). Not scored into the index.",
    "pillars": [
      "macro"
    ],
    "benchmarks": {},
    "normalization": "none",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "PCPIPCH": {
    "code": "PCPIPCH",
    "label": "Inflation (consumer prices)",
    "domain": "macro",
    "source": "IMF WEO",
    "unit": "%",
    "direction": -1,
    "interpretation": "High or volatile inflation reduces the purchasing power of health budgets and households. The 10% line is a warning reference, not a hard threshold.",
    "pillars": [
      "macro",
      "efficiency"
    ],
    "benchmarks": {
      "heuristic_caution": 10.0
    },
    "normalization": "peer_minmax",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "NY.GDP.PCAP.CD": {
    "code": "NY.GDP.PCAP.CD",
    "label": "GDP per capita (WB, current US$)",
    "domain": "macro",
    "source": "World Bank",
    "unit": "US$",
    "direction": 1,
    "interpretation": "Context / peer-grouping variable only \u2014 basis for World Bank income grouping. Not scored into the index.",
    "pillars": [
      "macro"
    ],
    "benchmarks": {},
    "normalization": "none",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "GC.REV.XGRT.GD.ZS": {
    "code": "GC.REV.XGRT.GD.ZS",
    "label": "Government revenue (excl. grants)",
    "domain": "revenue",
    "source": "World Bank",
    "unit": "% GDP",
    "direction": 1,
    "interpretation": "Total domestic public revenue excluding grants \u2014 the size of the public resource envelope before allocation decisions. The ~15%-of-GDP reference point applies to tax revenue specifically, so compare carefully against this broader measure.",
    "pillars": [
      "revenue",
      "macro",
      "debt"
    ],
    "benchmarks": {},
    "normalization": "peer_minmax",
    "reference_url": "https://data.worldbank.org/indicator/GC.REV.XGRT.GD.ZS",
    "available": true,
    "fallback_code": null
  },
  "GC.TAX.TOTL.GD.ZS": {
    "code": "GC.TAX.TOTL.GD.ZS",
    "label": "Tax revenue",
    "domain": "revenue",
    "source": "World Bank",
    "unit": "% GDP",
    "direction": 1,
    "interpretation": "Tax revenue is the most policy-actionable part of the public resource envelope. About 15% of GDP is often cited as a minimum reference for state capacity.",
    "pillars": [
      "revenue"
    ],
    "benchmarks": {
      "tax_capacity_tipping_point": 15.0
    },
    "normalization": "peer_minmax",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "GGR_NGDP": {
    "code": "GGR_NGDP",
    "label": "Government revenue (IMF)",
    "domain": "revenue",
    "source": "IMF WEO",
    "unit": "% GDP",
    "direction": 1,
    "interpretation": "IMF general-government revenue. Currently empty from the DataMapper API \u2014 falls back to the World Bank series.",
    "pillars": [
      "revenue",
      "macro"
    ],
    "benchmarks": {},
    "normalization": "peer_minmax",
    "reference_url": "",
    "available": false,
    "fallback_code": "GC.REV.XGRT.GD.ZS"
  },
  "GHED_gghed_gge": {
    "code": "GHED_gghed_gge",
    "label": "Government health spending (% of govt budget)",
    "domain": "prioritisation",
    "source": "WHO GHED",
    "unit": "% GGE",
    "direction": 1,
    "interpretation": "Shows the share of government spending allocated to health. The Abuja Declaration set a 15% target for African Union members.",
    "pillars": [
      "prioritisation"
    ],
    "benchmarks": {
      "Abuja": 15.0
    },
    "normalization": "peer_minmax",
    "reference_url": "https://apps.who.int/nha/database",
    "available": true,
    "fallback_code": null
  },
  "GHED_gghed_gdp": {
    "code": "GHED_gghed_gdp",
    "label": "Government health spending (% of GDP)",
    "domain": "prioritisation",
    "source": "WHO GHED",
    "unit": "% GDP",
    "direction": 1,
    "interpretation": "Shows public health spending relative to the whole economy, combining the size of the public budget and the priority given to health. Around 5% of GDP from public sources is often used as a reference for progress toward UHC, but it is not a binding global standard.",
    "pillars": [
      "prioritisation",
      "efficiency"
    ],
    "benchmarks": {
      "UHC_progress_guide_5pct": 5.0
    },
    "normalization": "peer_minmax",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "GHED_gghed_pc_usd": {
    "code": "GHED_gghed_pc_usd",
    "label": "Government health spending per capita",
    "domain": "prioritisation",
    "source": "WHO GHED",
    "unit": "US$",
    "direction": 1,
    "interpretation": "Absolute public resourcing per person \u2014 most directly comparable to a costed benefit package. Reference US$86 is the Chatham House essential-package estimate in 2012 prices (McIntyre & Meheus 2014); later costings differ (e.g. Stenberg et al. 2017 \u2248US$112 by 2030), so treat as an order-of-magnitude anchor.",
    "pillars": [
      "prioritisation"
    ],
    "benchmarks": {
      "essential_package_2012usd": 86.0
    },
    "normalization": "peer_minmax",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "GHED_gge_gdp": {
    "code": "GHED_gge_gdp",
    "label": "Government expenditure (% of GDP)",
    "domain": "prioritisation",
    "source": "WHO GHED",
    "unit": "% GDP",
    "direction": 0,
    "interpretation": "Size of the total budget envelope within which health competes for share.",
    "pillars": [
      "prioritisation",
      "macro"
    ],
    "benchmarks": {},
    "normalization": "peer_minmax",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "GHED_ext_che": {
    "code": "GHED_ext_che",
    "label": "External health spending (% of CHE)",
    "domain": "external",
    "source": "WHO GHED",
    "unit": "% CHE",
    "direction": -1,
    "interpretation": "Shows how much current health expenditure is funded by external sources. High shares can create transition risk if aid declines. The ~20% watch line is a heuristic from the transition literature (Gavi/Global Fund eligibility & co-financing), not a formal global standard.",
    "pillars": [
      "external"
    ],
    "benchmarks": {
      "heuristic_transition_watch": 20.0
    },
    "normalization": "peer_minmax",
    "reference_url": "https://apps.who.int/nha/database",
    "available": true,
    "fallback_code": null
  },
  "SH.XPD.EHEX.CH.ZS": {
    "code": "SH.XPD.EHEX.CH.ZS",
    "label": "External health expenditure (% of CHE, WB)",
    "domain": "external",
    "source": "World Bank",
    "unit": "% CHE",
    "direction": -1,
    "interpretation": "World Bank cross-check on donor dependency.",
    "pillars": [
      "external"
    ],
    "benchmarks": {},
    "normalization": "peer_minmax",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "DT.ODA.ALLD.CD": {
    "code": "DT.ODA.ALLD.CD",
    "label": "Net ODA received",
    "domain": "external",
    "source": "World Bank",
    "unit": "US$",
    "direction": 0,
    "interpretation": "Context only \u2014 absolute ODA in US$ is not comparable across economies of different size and is directionally ambiguous (more aid \u2260 more or less fiscal space), so it is not scored into the index.",
    "pillars": [
      "external"
    ],
    "benchmarks": {},
    "normalization": "none",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "GGXWDG_NGDP": {
    "code": "GGXWDG_NGDP",
    "label": "Government gross debt",
    "domain": "debt",
    "source": "IMF WEO",
    "unit": "% GDP",
    "direction": -1,
    "interpretation": "Debt thresholds vary by country context and debt-carrying capacity. Rising debt can reduce future health fiscal space through higher debt service. The reference lines (~60% of GDP, EU/IMF emerging-market scrutiny; ~55%, IMF\u2013World Bank LIC framework for medium capacity) are heuristics, not hard thresholds.",
    "pillars": [
      "debt"
    ],
    "benchmarks": {
      "EU_EM_line": 60.0,
      "LIC_DSF_medium_capacity": 55.0
    },
    "normalization": "peer_minmax",
    "reference_url": "https://www.imf.org/external/datamapper/datasets/WEO",
    "available": true,
    "fallback_code": null
  },
  "GGXCNL_NGDP": {
    "code": "GGXCNL_NGDP",
    "label": "Fiscal balance (surplus or deficit)",
    "domain": "debt",
    "source": "IMF WEO",
    "unit": "% GDP",
    "direction": 1,
    "interpretation": "Persistent large deficits can raise debt-service pressures. The -3%-of-GDP line is a fiscal-rule reference point (EU Stability & Growth Pact), not a universal danger threshold.",
    "pillars": [
      "debt",
      "macro"
    ],
    "benchmarks": {
      "EU_fiscal_rule": -3.0
    },
    "normalization": "peer_minmax",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "DT.TDS.DECT.GN.ZS": {
    "code": "DT.TDS.DECT.GN.ZS",
    "label": "External debt service",
    "domain": "debt",
    "source": "World Bank",
    "unit": "% GNI",
    "direction": -1,
    "interpretation": "External debt service can crowd out public spending, including health. This measure excludes domestic debt service.",
    "pillars": [
      "debt"
    ],
    "benchmarks": {},
    "normalization": "peer_minmax",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "DT.DOD.DECT.CD": {
    "code": "DT.DOD.DECT.CD",
    "label": "External debt stock",
    "domain": "debt",
    "source": "World Bank",
    "unit": "US$",
    "direction": -1,
    "interpretation": "Context only \u2014 absolute external obligations in US$ are not comparable across economies of different size; the %-of-GDP debt measures carry the scoring.",
    "pillars": [
      "debt"
    ],
    "benchmarks": {},
    "normalization": "none",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "GC.DOD.TOTL.GD.ZS": {
    "code": "GC.DOD.TOTL.GD.ZS",
    "label": "Central government debt",
    "domain": "debt",
    "source": "World Bank",
    "unit": "% GDP",
    "direction": -1,
    "interpretation": "Domestic + external central-government debt as a share of GDP.",
    "pillars": [
      "debt"
    ],
    "benchmarks": {},
    "normalization": "peer_minmax",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "GGXONLB_NGDP": {
    "code": "GGXONLB_NGDP",
    "label": "Primary balance",
    "domain": "debt",
    "source": "IMF WEO",
    "unit": "% GDP",
    "direction": 1,
    "interpretation": "Balance excluding interest \u2014 the lever a government actually controls. Currently empty from DataMapper.",
    "pillars": [
      "debt"
    ],
    "benchmarks": {},
    "normalization": "peer_minmax",
    "reference_url": "",
    "available": false,
    "fallback_code": null
  },
  "SH.DYN.MORT": {
    "code": "SH.DYN.MORT",
    "label": "Under-5 mortality",
    "domain": "efficiency",
    "source": "World Bank",
    "unit": "per 1,000",
    "direction": -1,
    "interpretation": "Outcome feeding the spending-efficiency proxy (attainment relative to spend); also shown raw.",
    "pillars": [
      "efficiency"
    ],
    "benchmarks": {},
    "normalization": "none",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "SH.STA.MMRT": {
    "code": "SH.STA.MMRT",
    "label": "Maternal mortality ratio",
    "domain": "efficiency",
    "source": "World Bank",
    "unit": "per 100,000",
    "direction": -1,
    "interpretation": "Outcome feeding the spending-efficiency proxy; high-sensitivity measure of system effectiveness.",
    "pillars": [
      "efficiency"
    ],
    "benchmarks": {},
    "normalization": "none",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "SP.DYN.LE00.IN": {
    "code": "SP.DYN.LE00.IN",
    "label": "Life expectancy at birth",
    "domain": "efficiency",
    "source": "World Bank",
    "unit": "years",
    "direction": 1,
    "interpretation": "Summary outcome feeding the spending-efficiency proxy.",
    "pillars": [
      "efficiency"
    ],
    "benchmarks": {},
    "normalization": "none",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "UHC_INDEX_REPORTED": {
    "code": "UHC_INDEX_REPORTED",
    "label": "UHC Service Coverage Index",
    "domain": "efficiency",
    "source": "WHO GHO",
    "unit": "0\u2013100",
    "direction": 1,
    "interpretation": "Service-coverage attainment feeding the spending-efficiency proxy. SDG 3.8.1 targets coverage for all by 2030; the ~80 line is WHO's interim 'high coverage' marker (GPW13 / UHC monitoring), not the SDG target value itself.",
    "pillars": [
      "efficiency"
    ],
    "benchmarks": {
      "WHO_interim_high_coverage": 80.0
    },
    "normalization": "none",
    "reference_url": "",
    "available": true,
    "fallback_code": "SH.UHC.SRVS.CV.XD"
  },
  "PEFA16_OVERALL_AVG": {
    "code": "PEFA16_OVERALL_AVG",
    "label": "PEFA overall score",
    "domain": "pfm",
    "source": "PEFA 2016",
    "unit": "1\u20134",
    "direction": 1,
    "interpretation": "Overall public financial management quality \u2014 can the budget be executed as planned?",
    "pillars": [
      "pfm"
    ],
    "benchmarks": {},
    "normalization": "fixed_minmax",
    "reference_url": "https://www.pefa.org",
    "available": true,
    "fallback_code": null
  },
  "PEFA16_BUDGET_RELIAB_AVG": {
    "code": "PEFA16_BUDGET_RELIAB_AVG",
    "label": "PEFA budget reliability",
    "domain": "pfm",
    "source": "PEFA 2016",
    "unit": "1\u20134",
    "direction": 1,
    "interpretation": "Do actuals match the approved budget? Weak reliability means appropriated health money may not arrive.",
    "pillars": [
      "pfm"
    ],
    "benchmarks": {},
    "normalization": "fixed_minmax",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "PEFA16_PILLAR3_AVG": {
    "code": "PEFA16_PILLAR3_AVG",
    "label": "PEFA budget execution",
    "domain": "pfm",
    "source": "PEFA 2016",
    "unit": "1\u20134",
    "direction": 1,
    "interpretation": "Shows whether public funds can be released, controlled, and spent as planned.",
    "pillars": [
      "pfm",
      "efficiency"
    ],
    "benchmarks": {},
    "normalization": "fixed_minmax",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "IQ.CPA.FINQ.XQ": {
    "code": "IQ.CPA.FINQ.XQ",
    "label": "CPIA financial management quality",
    "domain": "pfm",
    "source": "CPIA",
    "unit": "1\u20136",
    "direction": 1,
    "interpretation": "World Bank assessment of budgetary and financial management quality (IDA countries).",
    "pillars": [
      "pfm"
    ],
    "benchmarks": {},
    "normalization": "fixed_minmax",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "IQ.CPA.IRAI.XQ": {
    "code": "IQ.CPA.IRAI.XQ",
    "label": "CPIA policy & institutions (overall)",
    "domain": "pfm",
    "source": "CPIA",
    "unit": "1\u20136",
    "direction": 1,
    "interpretation": "Overall institutional and policy quality \u2014 conditioning variable for whether spend converts to outcomes.",
    "pillars": [
      "pfm"
    ],
    "benchmarks": {},
    "normalization": "peer_minmax",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "GOV_WGI_GE.EST": {
    "code": "GOV_WGI_GE.EST",
    "label": "Government effectiveness (WGI)",
    "domain": "pfm",
    "source": "WGI",
    "unit": "z-score",
    "direction": 1,
    "interpretation": "Strong implementation capacity helps public health spending translate into services.",
    "pillars": [
      "pfm"
    ],
    "benchmarks": {
      "midpoint": 0.0
    },
    "normalization": "zscore",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "GOV_WGI_CC.EST": {
    "code": "GOV_WGI_CC.EST",
    "label": "Control of corruption (WGI)",
    "domain": "pfm",
    "source": "WGI",
    "unit": "z-score",
    "direction": 1,
    "interpretation": "Weak control of corruption increases the risk that public resources do not reach intended services.",
    "pillars": [
      "pfm"
    ],
    "benchmarks": {},
    "normalization": "zscore",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "GOV_WGI_RL.EST": {
    "code": "GOV_WGI_RL.EST",
    "label": "Rule of law (WGI)",
    "domain": "pfm",
    "source": "WGI",
    "unit": "z-score",
    "direction": 1,
    "interpretation": "Institutional reliability underpinning predictable budget execution.",
    "pillars": [
      "pfm"
    ],
    "benchmarks": {},
    "normalization": "zscore",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  },
  "WB_FCV_STATUS": {
    "code": "WB_FCV_STATUS",
    "label": "Fragile/conflict status",
    "domain": "pfm",
    "source": "World Bank FCV",
    "unit": "0/1",
    "direction": -1,
    "interpretation": "FCV settings face structurally constrained fiscal space and execution capacity.",
    "pillars": [
      "pfm"
    ],
    "benchmarks": {},
    "normalization": "none",
    "reference_url": "",
    "available": true,
    "fallback_code": null
  }
};
